# fly.toml app configuration file generated for tc-mcp on 2025-07-15T09:18:24+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tc-mcp'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  # auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
